version: '3.8'

services:
  # Application
  pharmacy-app:
    build: .
    container_name: pharmacy-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/var/log/pharmacy
    depends_on:
      - pharmacy-db
    networks:
      - pharmacy-network
    healthcheck:
      test: ["CMD", "node", "scripts/health-check.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Database
  pharmacy-db:
    image: mysql:8.0
    container_name: pharmacy-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pharmacy-db-data:/var/lib/mysql
      - ./backups:/backups
    ports:
      - "3306:3306"
    networks:
      - pharmacy-network
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max_connections=200
      --innodb_buffer_pool_size=256M

  # Redis (Optional - for caching and sessions)
  pharmacy-redis:
    image: redis:7-alpine
    container_name: pharmacy-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - pharmacy-redis-data:/data
    networks:
      - pharmacy-network
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}

  # Nginx (Reverse Proxy)
  pharmacy-nginx:
    image: nginx:alpine
    container_name: pharmacy-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - pharmacy-app
    networks:
      - pharmacy-network

volumes:
  pharmacy-db-data:
    driver: local
  pharmacy-redis-data:
    driver: local

networks:
  pharmacy-network:
    driver: bridge
