#!/bin/bash
# SendGrid SMTP Configuration Guide for Global Pharma Trading

echo "🔥 SENDGRID SMTP SETUP GUIDE"
echo "============================"
echo ""
echo "STEP 1: Create SendGrid Account"
echo "1. Go to: https://sendgrid.com/"
echo "2. Sign up for free account"
echo "3. Verify your email address"
echo ""
echo "STEP 2: Create API Key"
echo "1. Go to Settings → API Keys"
echo "2. Click 'Create API Key'"
echo "3. Name it: 'Global Pharma Trading SMTP'"
echo "4. Choose 'Restricted Access'"
echo "5. Grant 'Mail Send' permissions"
echo "6. Copy the API key (save it securely!)"
echo ""
echo "STEP 3: Add Environment Variables to Vercel"
echo "Run these commands one by one:"
echo ""
echo "vercel env add SMTP_HOST"
echo "# Enter: smtp.sendgrid.net"
echo ""
echo "vercel env add SMTP_PORT"
echo "# Enter: 587"
echo ""
echo "vercel env add SMTP_USER"
echo "# Enter: apikey"
echo ""
echo "vercel env add SMTP_PASS"
echo "# Enter: YOUR_SENDGRID_API_KEY_HERE"
echo ""
echo "vercel env add SMTP_FROM"
echo "# Enter: \"Global Pharma Trading <noreply@globalpharmatrading.co.uk>\""
echo ""
echo "STEP 4: Redeploy"
echo "vercel --prod"
echo ""
echo "STEP 5: Test Email"
echo "Visit: https://globalpharmatrading.co.uk/api/auth/send-verification"
echo ""
